POST http://localhost:8080/gzipCompress
Content-Type: application/json
Accept: text/plain

{
  "delay": 50,
  "delayVariance": 250,
  "properties": {
    "id": {
      "value": "#{uuid}"
    },
    "email": {
      "value": "#{email}"
    },
    "age": {
      "value": "#{int:min=2,max=10}"
    },
    "active": {
      "type": "STRING",
      "value": "#{boolean}"
    },
    "name": {
      "type": "ARRAY",
      "count": 2,
      "countVariance": 1,
      "properties": {
        "first": {
          "value": "#{firstname}"
        },
        "last": {
          "value": "#{lastname}"
        }
      }
    }
  }
}

###

GET http://localhost:8080/?g=H4sIAAAAAAAAAF2PPQuDMBCG_8t1zaBCl4CDU-nSwUqh41XTcpAPiYlUxP9eE4WqGcLxPk8udyM0QuIA_JywpXygJdS1AJ6FrLWmFdaR6ICPQE24e5R-5nAavadmgomBUEhyz2IUIX7EHpF2XJHOM6bwm6fJYtWO-ii6oQ3evSqvtwuwzcOXMVKgjr5GtbWLsiyes1wbr908_Fr910mPy7zJdm4_WIxC4_iDxCMPyYrD-QE-R4kNPgEAAA==
Accept: application/json

###
