POST http://localhost:8080/gzipCompress
Content-Type: application/json
Accept: text/plain

{
  "delay": "250ms",
  "delayVariance": "50ms",
  "properties": {
    "id": {
      "value": "#{uuid}"
    },
    "email": {
      "value": "#{email}"
    },
    "age": {
      "value": "#{int:min=2,max=10}"
    },
    "active": {
      "type": "STRING",
      "value": "#{boolean}"
    },
    "name": {
      "type": "ARRAY",
      "count": 2,
      "countVariance": 1,
      "properties": {
        "first": {
          "value": "#{firstname}"
        },
        "last": {
          "value": "#{lastname}"
        }
      }
    }
  }
}

###

GET http://localhost:8080/?g=H4sIAAAAAAAAAF2PPQuDMBCG_8t1dVChS8DBqXTpYEuh41Wv5SAfEhOpiP-9JgrWZgjJ-zyX3I3QkMQBBOTHVHWQLPc7WkZd05yvcWtNS9YxdSBG4CbsPUoflMPoPTcTTAmQQpZ7FqMI8U17xNoJxbrIE4WfIksXq3bcR9ENbfCut-p8Oc09bIVPYyShjr5G9WuXVVU-Zrk2XjsQ-XraJsr-h3mx7dy-sRiFh-MPEv95SFYc1hd91dskRgEAAA==
Accept: application/json

###
